// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaGCqRmV9hQuFkD-06vXyzk6XJ6ujXMOI',
    appId: '1:274063087309:web:b994d930b4e14b761fbb84',
    messagingSenderId: '274063087309',
    projectId: 'watch-vault-16b43',
    authDomain: 'watch-vault-16b43.firebaseapp.com',
    storageBucket: 'watch-vault-16b43.appspot.com',
    measurementId: 'G-BSKKH38KD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQjIhrPokVu1kMcy2qVc_pGSoz62sML_I',
    appId: '1:274063087309:android:aff3f7291ad669a81fbb84',
    messagingSenderId: '274063087309',
    projectId: 'watch-vault-16b43',
    storageBucket: 'watch-vault-16b43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwHqTd5HJKF3lonZ32nwIeiqQ2X7Tz_oY',
    appId: '1:274063087309:ios:9e34f888529db9271fbb84',
    messagingSenderId: '274063087309',
    projectId: 'watch-vault-16b43',
    storageBucket: 'watch-vault-16b43.appspot.com',
    iosBundleId: 'com.watchvault.app001',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwHqTd5HJKF3lonZ32nwIeiqQ2X7Tz_oY',
    appId: '1:274063087309:ios:1cc434fff3f2632d1fbb84',
    messagingSenderId: '274063087309',
    projectId: 'watch-vault-16b43',
    storageBucket: 'watch-vault-16b43.appspot.com',
    iosBundleId: 'com.watchvault.app001.RunnerTests',
  );
}
